services:
  - type: web
    name: curtain-showcase
    env: node
    rootDir: src/server
    buildCommand: npm install
    startCommand: node src/deploy.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
